---
  apache_enablerepo: ""

  apache_listen_ip: "*"
  apache_listen_port: 80
  apache_listen_port_ssl: 443

  apache_create_vhosts: true
  apache_vhosts_filename: "vhosts.conf"
  apache_vhosts_template: "vhosts.conf.j2"

  # On Debian/Ubuntu, a default virtualhost is included in Apache's configuration.
  # Set this to `true` to remove that default.
  apache_remove_default_vhost: false

  apache_global_vhost_settings: |
    DirectoryIndex index.php index.html
  apache_vhosts:
    # Additional properties:
    # 'serveradmin, serveralias, allow_override, options, extra_parameters'.
    - servername: "www.webservertest123.com"
      documentroot: "/var/www/html"

  apache_allow_override: "All"
  apache_options: "-Indexes +FollowSymLinks"

  apache_vhosts_ssl: []
  # Additional properties:
  # 'serveradmin, serveralias, allow_override, options, extra_parameters'.
   - servername: "www.webservertest123.com",
     documentroot: "/var/www/html",
     certificate_file: "/etc/ssl/crt/webserver.crt",
     certificate_key_file: "/etc/ssl/private/webserver.pem"

  apache_ignore_missing_ssl_certificate: true

  apache_ssl_protocol: "All -SSLv2 -SSLv3"
  apache_ssl_cipher_suite: "AES256+EECDH:AES256+EDH"

  # Set initial apache state. Recommended values: `started` or `stopped`
  apache_state: started

  # Set apache state when configuration changes are made. Recommended values:
  # `restarted` or `reloaded`
  apache_restart_state: restarted

  # Apache package state; use `present` to make sure it's installed, or `latest`
  # if you want to upgrade or switch versions using a new repo.
  apache_packages_state: present
